export const fakeTasks = [
  {
    id: 1,
    isPrimary: true,
    title: "Today work",
    bodyType: "text",
    bodyText:
      "Ensure code meets quality standards and adheres to best practices. And also, finalize presentation materials to showcase project progress to the client.",
    date: "22 Mar, 01:12 PM",
    isPinned: true,
  },
  {
    id: 2,
    isPrimary: false,
    title: "Review Code for Feature X",
    bodyType: "text",
    bodyText:
      "Ensure code meets quality standards and adheres to best practices.",
    date: "24 Apr, 02:39 AM",
    isPinned: false,
  },
  {
    id: 3,
    isPrimary: false,
    title: "Prepare for Client Presentation",
    bodyType: "text",
    bodyText:
      "Finalize presentation materials to showcase project progress to the client.",
    date: "26 Jan, 05:45 PM",
    isPinned: false,
  },
  {
    id: 4,
    isPrimary: false,
    title: "Bug Fix for Feature Y",
    bodyType: "text",
    bodyText: "Identify and resolve the reported bug in Feature Y.",
    date: "11 Jun, 12:09 AM",
    isPinned: false,
  },
  {
    id: 5,
    isPrimary: false,
    title: "Prepare for Client Presentation",
    bodyType: "text",
    bodyText:
      "Finalize presentation materials to showcase project progress to the client.",
    date: "7 Jun, 02:33 AM",
    isPinned: false,
  },

  {
    id: 6,
    isPrimary: false,
    title: "Code Review (X)",
    bodyType: "text",
    bodyText: "Review code for Feature X.",
    date: "12 May, 09:15 PM",
    isPinned: false,
  },
  {
    id: 7,
    isPrimary: false,
    title: "Client Meeting Prep",
    bodyType: "text",
    bodyText: "Finalize materials for client presentation.",
    date: "14 May, 03:22 PM",
    isPinned: false,
  },
  {
    id: 8,
    isPrimary: false,
    title: "Fix Bug (Y)",
    bodyType: "text",
    bodyText: "Identify and resolve bug in Feature Y.",
    date: "15 May, 11:48 AM",
    isPinned: false,
  },
  {
    id: 9,
    isPrimary: false,
    title: "UI/UX Design",
    bodyType: "text",
    bodyText: "Apply design principles.",
    date: "16 May, 08:30 AM",
    isPinned: false,
  },
  {
    id: 10,
    isPrimary: false,
    title: "Meeting Prep",
    bodyType: "text",
    date: "17 May, 02:10 PM",
    isPinned: false,
  },
];
